// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file transcript.proto (package preppal.transcript, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file transcript.proto.
 */
export const file_transcript: GenFile = /*@__PURE__*/
  fileDesc("ChB0cmFuc2NyaXB0LnByb3RvEhJwcmVwcGFsLnRyYW5zY3JpcHQiNQoKVHJhbnNjcmlwdBInCgV0dXJucxgBIAMoCzIYLnByZXBwYWwudHJhbnNjcmlwdC5UdXJuIlsKBFR1cm4SLAoHc3BlYWtlchgBIAEoDjIbLnByZXBwYWwudHJhbnNjcmlwdC5TcGVha2VyEg8KB2NvbnRlbnQYAiABKAkSFAoMdGltZXN0YW1wX21zGAMgASgDKjQKB1NwZWFrZXISFwoTU1BFQUtFUl9VTlNQRUNJRklFRBAAEggKBFVTRVIQARIGCgJBSRACYgZwcm90bzM");

/**
 * Complete transcript for an interview session
 * Stored as a single binary blob in the database
 *
 * @generated from message preppal.transcript.Transcript
 */
export type Transcript = Message<"preppal.transcript.Transcript"> & {
  /**
   * @generated from field: repeated preppal.transcript.Turn turns = 1;
   */
  turns: Turn[];
};

/**
 * Describes the message preppal.transcript.Transcript.
 * Use `create(TranscriptSchema)` to create a new message.
 */
export const TranscriptSchema: GenMessage<Transcript> = /*@__PURE__*/
  messageDesc(file_transcript, 0);

/**
 * A single conversational turn by one speaker
 *
 * @generated from message preppal.transcript.Turn
 */
export type Turn = Message<"preppal.transcript.Turn"> & {
  /**
   * @generated from field: preppal.transcript.Speaker speaker = 1;
   */
  speaker: Speaker;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * Unix milliseconds
   *
   * @generated from field: int64 timestamp_ms = 3;
   */
  timestampMs: bigint;
};

/**
 * Describes the message preppal.transcript.Turn.
 * Use `create(TurnSchema)` to create a new message.
 */
export const TurnSchema: GenMessage<Turn> = /*@__PURE__*/
  messageDesc(file_transcript, 1);

/**
 * Speaker identity
 *
 * @generated from enum preppal.transcript.Speaker
 */
export enum Speaker {
  /**
   * @generated from enum value: SPEAKER_UNSPECIFIED = 0;
   */
  SPEAKER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: AI = 2;
   */
  AI = 2,
}

/**
 * Describes the enum preppal.transcript.Speaker.
 */
export const SpeakerSchema: GenEnum<Speaker> = /*@__PURE__*/
  enumDesc(file_transcript, 0);

